// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocklist.sql

package sqlstore

import (
	"context"

	"github.com/google/uuid"
)

const createBlocklistEntry = `-- name: CreateBlocklistEntry :one
insert into blocklist (pattern, kind)
values ($1, $2)
returning id, pattern, kind, created_at
`

type CreateBlocklistEntryParams struct {
	Pattern string `json:"pattern"`
	Kind    string `json:"kind"`
}

func (q *Queries) CreateBlocklistEntry(ctx context.Context, arg CreateBlocklistEntryParams) (Blocklist, error) {
	row := q.db.QueryRow(ctx, createBlocklistEntry, arg.Pattern, arg.Kind)
	var i Blocklist
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlocklistEntry = `-- name: DeleteBlocklistEntry :exec
delete from blocklist
where id = $1
`

func (q *Queries) DeleteBlocklistEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlocklistEntry, id)
	return err
}

const getBlocklistEntryByPattern = `-- name: GetBlocklistEntryByPattern :one
select id, pattern, kind, created_at from blocklist
where pattern = $1
`

func (q *Queries) GetBlocklistEntryByPattern(ctx context.Context, pattern string) (Blocklist, error) {
	row := q.db.QueryRow(ctx, getBlocklistEntryByPattern, pattern)
	var i Blocklist
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const isBlocked = `-- name: IsBlocked :one
select exists (
    select 1 from blocklist
    where (kind = 'url' and pattern = $1)
       or (kind = 'domain' and ($2::text = pattern or $2::text like '%.' || pattern))
) as blocked
`

type IsBlockedParams struct {
	Pattern string `json:"pattern"`
	Column2 string `json:"column_2"`
}

func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.Pattern, arg.Column2)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listBlocklistEntries = `-- name: ListBlocklistEntries :many
select id, pattern, kind, created_at from blocklist
order by created_at desc
`

func (q *Queries) ListBlocklistEntries(ctx context.Context) ([]Blocklist, error) {
	rows, err := q.db.Query(ctx, listBlocklistEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blocklist
	for rows.Next() {
		var i Blocklist
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
