// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discussions.sql

package sqlstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeDiscussionJob = `-- name: CompleteDiscussionJob :exec
update urls
set next_check_at   = $2,
    last_checked_at = now(),
    check_count     = $3,
    empty_count     = $4
where id = $1
`

type CompleteDiscussionJobParams struct {
	ID          uuid.UUID          `json:"id"`
	NextCheckAt pgtype.Timestamptz `json:"next_check_at"`
	CheckCount  int32              `json:"check_count"`
	EmptyCount  int32              `json:"empty_count"`
}

func (q *Queries) CompleteDiscussionJob(ctx context.Context, arg CompleteDiscussionJobParams) error {
	_, err := q.db.Exec(ctx, completeDiscussionJob,
		arg.ID,
		arg.NextCheckAt,
		arg.CheckCount,
		arg.EmptyCount,
	)
	return err
}

const enqueueDiscussionJob = `-- name: EnqueueDiscussionJob :exec
update urls set next_check_at = now() where id = $1
`

func (q *Queries) EnqueueDiscussionJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enqueueDiscussionJob, id)
	return err
}

const listDiscussionsForURL = `-- name: ListDiscussionsForURL :many
select id, url_id, source, title, discussion_url, score, comment_count, found_at
from url_discussions
where url_id = $1
order by score desc, found_at desc
`

func (q *Queries) ListDiscussionsForURL(ctx context.Context, urlID uuid.UUID) ([]UrlDiscussion, error) {
	rows, err := q.db.Query(ctx, listDiscussionsForURL, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UrlDiscussion
	for rows.Next() {
		var i UrlDiscussion
		if err := rows.Scan(
			&i.ID,
			&i.URLID,
			&i.Source,
			&i.Title,
			&i.DiscussionUrl,
			&i.Score,
			&i.CommentCount,
			&i.FoundAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueURLs = `-- name: ListDueURLs :many
select id, url, check_count, empty_count
from urls
where next_check_at <= now()
order by next_check_at
limit 500
`

type ListDueURLsRow struct {
	ID         uuid.UUID `json:"id"`
	Url        string    `json:"url"`
	CheckCount int32     `json:"check_count"`
	EmptyCount int32     `json:"empty_count"`
}

func (q *Queries) ListDueURLs(ctx context.Context) ([]ListDueURLsRow, error) {
	rows, err := q.db.Query(ctx, listDueURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueURLsRow
	for rows.Next() {
		var i ListDueURLsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.CheckCount,
			&i.EmptyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDiscussion = `-- name: UpsertDiscussion :exec
insert into url_discussions (url_id, source, title, discussion_url, score, comment_count)
values ($1, $2, $3, $4, $5, $6)
on conflict (url_id, discussion_url) do update
	set score         = excluded.score,
	    comment_count = excluded.comment_count
`

type UpsertDiscussionParams struct {
	URLID         uuid.UUID `json:"url_id"`
	Source        string    `json:"source"`
	Title         string    `json:"title"`
	DiscussionUrl string    `json:"discussion_url"`
	Score         int32     `json:"score"`
	CommentCount  int32     `json:"comment_count"`
}

func (q *Queries) UpsertDiscussion(ctx context.Context, arg UpsertDiscussionParams) error {
	_, err := q.db.Exec(ctx, upsertDiscussion,
		arg.URLID,
		arg.Source,
		arg.Title,
		arg.DiscussionUrl,
		arg.Score,
		arg.CommentCount,
	)
	return err
}
