// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimJobRun = `-- name: ClaimJobRun :one
update job_configs
set    locked_until = $2,
       next_run_at  = $3
where  job_name = $1
  and  next_run_at <= now()
  and  locked_until <= now()
returning job_name
`

type ClaimJobRunParams struct {
	JobName     string             `json:"job_name"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	NextRunAt   pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) ClaimJobRun(ctx context.Context, arg ClaimJobRunParams) (string, error) {
	row := q.db.QueryRow(ctx, claimJobRun, arg.JobName, arg.LockedUntil, arg.NextRunAt)
	var job_name string
	err := row.Scan(&job_name)
	return job_name, err
}

const completeJobRun = `-- name: CompleteJobRun :exec
update job_runs
set completed_at = $2,
    error        = $3,
    metadata     = $4
where id = $1
`

type CompleteJobRunParams struct {
	ID          uuid.UUID          `json:"id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       *string            `json:"error"`
	Metadata    []byte             `json:"metadata"`
}

func (q *Queries) CompleteJobRun(ctx context.Context, arg CompleteJobRunParams) error {
	_, err := q.db.Exec(ctx, completeJobRun,
		arg.ID,
		arg.CompletedAt,
		arg.Error,
		arg.Metadata,
	)
	return err
}

const createJobRun = `-- name: CreateJobRun :one
insert into job_runs (job_name, started_at)
values ($1, $2)
returning id
`

type CreateJobRunParams struct {
	JobName   string             `json:"job_name"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateJobRun(ctx context.Context, arg CreateJobRunParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createJobRun, arg.JobName, arg.StartedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getJobConfig = `-- name: GetJobConfig :one
select job_name, next_run_at, locked_until
from job_configs
where job_name = $1
`

func (q *Queries) GetJobConfig(ctx context.Context, jobName string) (JobConfig, error) {
	row := q.db.QueryRow(ctx, getJobConfig, jobName)
	var i JobConfig
	err := row.Scan(&i.JobName, &i.NextRunAt, &i.LockedUntil)
	return i, err
}

const listJobRuns = `-- name: ListJobRuns :many
select id, job_name, started_at, completed_at, error, metadata
from job_runs
where job_name = $1
order by started_at desc
limit $2
`

type ListJobRunsParams struct {
	JobName string `json:"job_name"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListJobRuns(ctx context.Context, arg ListJobRunsParams) ([]JobRun, error) {
	rows, err := q.db.Query(ctx, listJobRuns, arg.JobName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobRun
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.ID,
			&i.JobName,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobNextRun = `-- name: UpdateJobNextRun :exec
update job_configs
set next_run_at = $2
where job_name = $1
`

type UpdateJobNextRunParams struct {
	JobName   string             `json:"job_name"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateJobNextRun(ctx context.Context, arg UpdateJobNextRunParams) error {
	_, err := q.db.Exec(ctx, updateJobNextRun, arg.JobName, arg.NextRunAt)
	return err
}
