// Code generated by sqlc. DO NOT EDIT.

package sqlstore

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	PasswordDigest string    `json:"password_digest"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Session struct {
	Token     string    `json:"token"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Url is the deduplicated URL record. Per-user metadata lives in UserUrl.
type Url struct {
	ID        uuid.UUID `json:"id"`
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
}

// UserUrlRow is returned by join queries across urls + user_urls.
type UserUrlRow struct {
	ID          uuid.UUID `json:"id"`
	Url         string    `json:"url"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Tags        []string  `json:"tags"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Tag struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type UrlTag struct {
	UserID uuid.UUID `json:"user_id"`
	UrlID  uuid.UUID `json:"url_id"`
	TagID  uuid.UUID `json:"tag_id"`
}
