// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type APIKey struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DiscussionRun struct {
	ID          int32              `json:"id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	LastRunAt   pgtype.Timestamptz `json:"last_run_at"`
}

type DiscussionRunLog struct {
	ID          uuid.UUID          `json:"id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UrlCount    int32              `json:"url_count"`
	FoundCount  int32              `json:"found_count"`
}

type InviteCode struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	CreatedBy uuid.UUID          `json:"created_by"`
	UsedBy    pgtype.UUID        `json:"used_by"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	Token     string             `json:"token"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Tag struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Url struct {
	ID        uuid.UUID          `json:"id"`
	Url       string             `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UrlDiscussion struct {
	ID            uuid.UUID          `json:"id"`
	URLID         uuid.UUID          `json:"url_id"`
	Source        string             `json:"source"`
	Title         string             `json:"title"`
	DiscussionUrl string             `json:"discussion_url"`
	Score         int32              `json:"score"`
	CommentCount  int32              `json:"comment_count"`
	FoundAt       pgtype.Timestamptz `json:"found_at"`
}

type UrlDiscussionJob struct {
	ID            uuid.UUID          `json:"id"`
	URLID         uuid.UUID          `json:"url_id"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	CheckCount    int32              `json:"check_count"`
	EmptyCount    int32              `json:"empty_count"`
}

type UrlTag struct {
	UserID uuid.UUID `json:"user_id"`
	URLID  uuid.UUID `json:"url_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	PasswordDigest string             `json:"password_digest"`
	IsAdmin        bool               `json:"is_admin"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserUrl struct {
	UserID      uuid.UUID          `json:"user_id"`
	URLID       uuid.UUID          `json:"url_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
