// Code generated by sqlc. DO NOT EDIT.
// source: tags.sql

package sqlstore

import (
	"context"

	"github.com/google/uuid"
)

const upsertTag = `
insert into tags (name) values ($1)
on conflict (name) do update set name = excluded.name
returning id, name
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, name)
	var t Tag
	err := row.Scan(&t.ID, &t.Name)
	return t, err
}

type AddTagToURLParams struct {
	UserID uuid.UUID `json:"user_id"`
	URLID  uuid.UUID `json:"url_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

const addTagToURL = `
insert into url_tags (user_id, url_id, tag_id) values ($1, $2, $3)
on conflict do nothing
`

func (q *Queries) AddTagToURL(ctx context.Context, arg AddTagToURLParams) error {
	_, err := q.db.Exec(ctx, addTagToURL, arg.UserID, arg.URLID, arg.TagID)
	return err
}

const removeAllTagsFromURL = `delete from url_tags where user_id = $1 and url_id = $2`

func (q *Queries) RemoveAllTagsFromURL(ctx context.Context, userID, urlID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllTagsFromURL, userID, urlID)
	return err
}

const listTagNamesForURL = `
select t.name from tags t
join url_tags ut on ut.tag_id = t.id
where ut.user_id = $1 and ut.url_id = $2
order by t.name
`

func (q *Queries) ListTagNamesForURL(ctx context.Context, userID, urlID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listTagNamesForURL, userID, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var names []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		names = append(names, name)
	}
	return names, rows.Err()
}
