// Code generated by sqlc. DO NOT EDIT.
// source: urls.sql

package sqlstore

import (
	"context"

	"github.com/google/uuid"
)

type GetURLParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

const getURL = `
select u.id, u.url, uu.title, uu.description, uu.created_at, uu.updated_at
from urls u
join user_urls uu on uu.url_id = u.id
where u.id = $1 and uu.user_id = $2
`

func (q *Queries) GetURL(ctx context.Context, arg GetURLParams) (UserUrlRow, error) {
	row := q.db.QueryRow(ctx, getURL, arg.ID, arg.UserID)
	var u UserUrlRow
	err := row.Scan(&u.ID, &u.Url, &u.Title, &u.Description, &u.CreatedAt, &u.UpdatedAt)
	return u, err
}

const listURLs = `
select u.id, u.url, uu.title, uu.description, uu.created_at, uu.updated_at
from urls u
join user_urls uu on uu.url_id = u.id
where uu.user_id = $1
order by uu.created_at desc
`

func (q *Queries) ListURLs(ctx context.Context, userID uuid.UUID) ([]UserUrlRow, error) {
	rows, err := q.db.Query(ctx, listURLs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var urls []UserUrlRow
	for rows.Next() {
		var u UserUrlRow
		if err := rows.Scan(&u.ID, &u.Url, &u.Title, &u.Description, &u.CreatedAt, &u.UpdatedAt); err != nil {
			return nil, err
		}
		urls = append(urls, u)
	}
	return urls, rows.Err()
}

const upsertURL = `
insert into urls (url) values ($1)
on conflict (url) do update set url = excluded.url
returning id
`

func (q *Queries) UpsertURL(ctx context.Context, rawURL string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertURL, rawURL)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

type AddURLToUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	URLID       uuid.UUID `json:"url_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
}

const addURLToUser = `
insert into user_urls (user_id, url_id, title, description) values ($1, $2, $3, $4)
on conflict (user_id, url_id) do nothing
`

func (q *Queries) AddURLToUser(ctx context.Context, arg AddURLToUserParams) error {
	_, err := q.db.Exec(ctx, addURLToUser, arg.UserID, arg.URLID, arg.Title, arg.Description)
	return err
}

type UpdateUserURLParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	UserID      uuid.UUID `json:"user_id"`
	URLID       uuid.UUID `json:"url_id"`
}

const updateUserURL = `
update user_urls set title = $1, description = $2, updated_at = now()
where user_id = $3 and url_id = $4
returning url_id
`

func (q *Queries) UpdateUserURL(ctx context.Context, arg UpdateUserURLParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUserURL, arg.Title, arg.Description, arg.UserID, arg.URLID)
	var urlID uuid.UUID
	err := row.Scan(&urlID)
	return urlID, err
}

const removeURLFromUser = `delete from user_urls where user_id = $1 and url_id = $2`

func (q *Queries) RemoveURLFromUser(ctx context.Context, userID, urlID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeURLFromUser, userID, urlID)
	return err
}
