// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package sqlstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addURLToUser = `-- name: AddURLToUser :exec
insert into user_urls (user_id, url_id, title, description)
values ($1, $2, $3, $4)
on conflict (user_id, url_id) do nothing
`

type AddURLToUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	URLID       uuid.UUID `json:"url_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
}

func (q *Queries) AddURLToUser(ctx context.Context, arg AddURLToUserParams) error {
	_, err := q.db.Exec(ctx, addURLToUser,
		arg.UserID,
		arg.URLID,
		arg.Title,
		arg.Description,
	)
	return err
}

const getURL = `-- name: GetURL :one
select u.id, u.url, u.feed_url, uu.title, uu.description, uu.created_at, uu.updated_at
from urls u
join user_urls uu on uu.url_id = u.id
where u.id = $1 and uu.user_id = $2
`

type GetURLParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetURLRow struct {
	ID          uuid.UUID          `json:"id"`
	Url         string             `json:"url"`
	FeedUrl     string             `json:"feed_url"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetURL(ctx context.Context, arg GetURLParams) (GetURLRow, error) {
	row := q.db.QueryRow(ctx, getURL, arg.ID, arg.UserID)
	var i GetURLRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.FeedUrl,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listURLs = `-- name: ListURLs :many
select u.id, u.url, u.feed_url, uu.title, uu.description, uu.created_at, uu.updated_at
from urls u
join user_urls uu on uu.url_id = u.id
where uu.user_id = $1
order by uu.created_at desc
`

type ListURLsRow struct {
	ID          uuid.UUID          `json:"id"`
	Url         string             `json:"url"`
	FeedUrl     string             `json:"feed_url"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListURLs(ctx context.Context, userID uuid.UUID) ([]ListURLsRow, error) {
	rows, err := q.db.Query(ctx, listURLs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListURLsRow
	for rows.Next() {
		var i ListURLsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.FeedUrl,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsByCategory = `-- name: ListURLsByCategory :many
select distinct u.id, u.url, u.feed_url, uu.title, uu.description, uu.created_at, uu.updated_at
from urls u
join user_urls uu on uu.url_id = u.id
where uu.user_id = $1
  and (
    exists (
      select 1 from url_tags ut
      join tags t on t.id = ut.tag_id
      join category_members cm on cm.kind = 'tag' and cm.value = t.name
      where ut.user_id = $1 and ut.url_id = u.id and cm.category_id = $2
    )
    or exists (
      select 1 from category_members cm
      where cm.category_id = $2 and cm.kind = 'domain'
        and regexp_replace(u.url, '^https?://([^/?#]+).*$', '\1', 'i') = cm.value
    )
  )
order by uu.created_at desc
`

type ListURLsByCategoryParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

type ListURLsByCategoryRow struct {
	ID          uuid.UUID          `json:"id"`
	Url         string             `json:"url"`
	FeedUrl     string             `json:"feed_url"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListURLsByCategory(ctx context.Context, arg ListURLsByCategoryParams) ([]ListURLsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listURLsByCategory, arg.UserID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListURLsByCategoryRow
	for rows.Next() {
		var i ListURLsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.FeedUrl,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsByTag = `-- name: ListURLsByTag :many
select u.id, u.url, u.feed_url, uu.title, uu.description, uu.created_at, uu.updated_at
from urls u
join user_urls uu on uu.url_id = u.id
join url_tags ut on ut.url_id = u.id and ut.user_id = uu.user_id
join tags t on t.id = ut.tag_id
where uu.user_id = $1 and t.name = $2
order by uu.created_at desc
`

type ListURLsByTagParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

type ListURLsByTagRow struct {
	ID          uuid.UUID          `json:"id"`
	Url         string             `json:"url"`
	FeedUrl     string             `json:"feed_url"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListURLsByTag(ctx context.Context, arg ListURLsByTagParams) ([]ListURLsByTagRow, error) {
	rows, err := q.db.Query(ctx, listURLsByTag, arg.UserID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListURLsByTagRow
	for rows.Next() {
		var i ListURLsByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.FeedUrl,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeURLFromUser = `-- name: RemoveURLFromUser :exec
delete from user_urls where user_id = $1 and url_id = $2
`

type RemoveURLFromUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	URLID  uuid.UUID `json:"url_id"`
}

func (q *Queries) RemoveURLFromUser(ctx context.Context, arg RemoveURLFromUserParams) error {
	_, err := q.db.Exec(ctx, removeURLFromUser, arg.UserID, arg.URLID)
	return err
}

const setURLFeedURL = `-- name: SetURLFeedURL :exec
update urls set feed_url = $2 where id = $1
`

type SetURLFeedURLParams struct {
	ID      uuid.UUID `json:"id"`
	FeedUrl string    `json:"feed_url"`
}

func (q *Queries) SetURLFeedURL(ctx context.Context, arg SetURLFeedURLParams) error {
	_, err := q.db.Exec(ctx, setURLFeedURL, arg.ID, arg.FeedUrl)
	return err
}

const updateUserURL = `-- name: UpdateUserURL :one
update user_urls
set title = $1, description = $2, updated_at = now()
where user_id = $3 and url_id = $4
returning url_id
`

type UpdateUserURLParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	UserID      uuid.UUID `json:"user_id"`
	URLID       uuid.UUID `json:"url_id"`
}

func (q *Queries) UpdateUserURL(ctx context.Context, arg UpdateUserURLParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUserURL,
		arg.Title,
		arg.Description,
		arg.UserID,
		arg.URLID,
	)
	var url_id uuid.UUID
	err := row.Scan(&url_id)
	return url_id, err
}

const upsertURL = `-- name: UpsertURL :one
insert into urls (url)
values ($1)
on conflict (url) do update set url = excluded.url
returning id
`

func (q *Queries) UpsertURL(ctx context.Context, url string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertURL, url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
