// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlstore

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, password_digest, is_admin)
values ($1, $2, $3)
returning id, email, password_digest, is_admin, theme, font_size, created_at, updated_at
`

type CreateUserParams struct {
	Email          string `json:"email"`
	PasswordDigest string `json:"password_digest"`
	IsAdmin        bool   `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordDigest, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordDigest,
		&i.IsAdmin,
		&i.Theme,
		&i.FontSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
select id, email, password_digest, is_admin, theme, font_size, created_at, updated_at from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordDigest,
		&i.IsAdmin,
		&i.Theme,
		&i.FontSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_digest, is_admin, theme, font_size, created_at, updated_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordDigest,
		&i.IsAdmin,
		&i.Theme,
		&i.FontSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select id, email, password_digest, is_admin, theme, font_size, created_at, updated_at from users order by created_at desc
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordDigest,
			&i.IsAdmin,
			&i.Theme,
			&i.FontSize,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
update users
set email = $1, updated_at = now()
where id = $2
returning id, email, password_digest, is_admin, theme, font_size, created_at, updated_at
`

type UpdateUserParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordDigest,
		&i.IsAdmin,
		&i.Theme,
		&i.FontSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserFontSize = `-- name: UpdateUserFontSize :one
update users
set font_size = $1, updated_at = now()
where id = $2
returning id, email, password_digest, is_admin, theme, font_size, created_at, updated_at
`

type UpdateUserFontSizeParams struct {
	FontSize string    `json:"font_size"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserFontSize(ctx context.Context, arg UpdateUserFontSizeParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFontSize, arg.FontSize, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordDigest,
		&i.IsAdmin,
		&i.Theme,
		&i.FontSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
update users
set password_digest = $1, updated_at = now()
where id = $2
returning id, email, password_digest, is_admin, theme, font_size, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	PasswordDigest string    `json:"password_digest"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordDigest, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordDigest,
		&i.IsAdmin,
		&i.Theme,
		&i.FontSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTheme = `-- name: UpdateUserTheme :one
update users
set theme = $1, updated_at = now()
where id = $2
returning id, email, password_digest, is_admin, theme, font_size, created_at, updated_at
`

type UpdateUserThemeParams struct {
	Theme string    `json:"theme"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserTheme(ctx context.Context, arg UpdateUserThemeParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTheme, arg.Theme, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordDigest,
		&i.IsAdmin,
		&i.Theme,
		&i.FontSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
